//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodProgramar.LnkCapture.Data.BusinessObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodProgramar.LnkCapture.Data.BusinessObjects.Resources.LinkResources", typeof(LinkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😵 Eu vou te enviar este link na chat privado, porém antes preciso que você incie uma conversa comigo. Faz assim, clique neste nome @LnkCapture e depois no botão &quot;start&quot; ou &quot;começar&quot;, depois volte aqui e solicite o link novamente..
        /// </summary>
        internal static string ChatNotInitiatedException {
            get {
                return ResourceManager.GetString("ChatNotInitiatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não consigo te enviar uma mensagem em particular com o link. Acho que você me bloqueou 😢..
        /// </summary>
        internal static string ForbiddenException {
            get {
                return ResourceManager.GetString("ForbiddenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙄 Este link já passou por aqui...
        ///🤔Já mandaram este link!
        ///😪 Esse link não passou por aqui outro dia desses?
        ///😒 Bacana o link, mas já mandaram ele por aqui..
        /// </summary>
        internal static string LinkAlreadyExists {
            get {
                return ResourceManager.GetString("LinkAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😖 Cara! Esse link não abriu. Não vou salvar por enquanto não.
        ///😱Tem certeza que este link está certo? Não foi pra lugar nenhum.
        ///😵 Tem alguma coisa errada com este link..
        /// </summary>
        internal static string LinkInvalid {
            get {
                return ResourceManager.GetString("LinkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👍 Salvei seu link!
        ///👊 Deixa que eu guardo este link para você.
        ///😀 Guardei este endereço!
        ///💾 Este link não escapa, tá salvo!
        ///😜 Hum... Parece um conteúdo interessante. Deixa eu guardar aqui...
        ///😬 Tá salvo o link, em nome de Odin!
        ///🙏 Como emissário de São Longuinho, guardei o link pra ficar fácil de encontrar depois.
        ///👌 Opa! Guardei esse link.
        ///👜 Guardei o link no meu bolso aqui.
        ///✍ Bacana este link, vou guardar aqui pra não perder.
        ///🤗 Link salvo! Pode ir mandando que eu tô guardando..
        /// </summary>
        internal static string LinkSaved {
            get {
                return ResourceManager.GetString("LinkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👉 Com este endereço você consegue recuperar os links salvos no chat{0}:.
        /// </summary>
        internal static string LinksRecover {
            get {
                return ResourceManager.GetString("LinksRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😓 Alguma coisa deu errado aqui! Não consigo executar o que você me pediu. Tenta de novo mais tarde por favor..
        /// </summary>
        internal static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
    }
}
