//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodProgramar.LnkCapture.Data.BusinessObjects.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PodProgramar.LnkCapture.Data.BusinessObjects.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛔ Somente administradores do grupo podem definir as configurações..
        /// </summary>
        internal static string BotOptionNotAllowed {
            get {
                return ResourceManager.GetString("BotOptionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😔 Não consegui salvar a configuração neste momento. Por favor, tente novamente em alguns instantes..
        /// </summary>
        internal static string BotOptionNotSet {
            get {
                return ResourceManager.GetString("BotOptionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ter acesso ao gerenciador de links é preciso solicitar o endereço de acesso. Esta solicitação é feita diretamente no grupo através do comando /linksUrl@LnkCaptureBot. Uma vez que você executar este comando eu vou te enviar aqui no chat privado o endereço de acesso. 
        ///
        ///Eu preciso te enviar de forma privada para que outras pessoas não vejam este link, ele é seu passaporte para o gerenciador de links. Não será solicitado usuário ou senha, o endereço é tudo que você precisa. 
        ///
        ///Um endereço diferente é ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Comandos para o Administrador do grupo
        ///
        ///`/disableSavedMsg` - Desativa confirmação de salvamento
        ///`/disableLinkAlreadyExistsMsg` - Desativa mensagens de link existente
        ///`/disableInvalidLinkMsg` - Desativa mensagens de link inválido
        ///`/enableSavedMsg` - Ativa confirmação de salvamento
        ///`/enableLinkAlreadyExistsMsg` - Ativa mensagens de link existente
        ///`/enableInvalidLinkMsg` - Ativa mensagens de link inválido.
        /// </summary>
        internal static string HelpAdmin {
            get {
                return ResourceManager.GetString("HelpAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eu enviei a mensagem de ajuda em uma mensagem privada..
        /// </summary>
        internal static string HelpToChat {
            get {
                return ResourceManager.GetString("HelpToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo bem! Não vou informar que o link é inválido..
        /// </summary>
        internal static string InvalidLinkMessageDisabled {
            get {
                return ResourceManager.GetString("InvalidLinkMessageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo bem! Vou informar que o link é inválido..
        /// </summary>
        internal static string InvalidLinkMessageEnabled {
            get {
                return ResourceManager.GetString("InvalidLinkMessageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🙄 Este link já passou por aqui...
        ///🤔 Já mandaram este link!
        ///😪 Esse link não passou por aqui outro dia desses?
        ///😒 Bacana o link, mas já mandaram ele por aqui..
        /// </summary>
        internal static string LinkAlreadyExists {
            get {
                return ResourceManager.GetString("LinkAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certo! Não vou avisar que o link já existe. Mesmo assim não vou salvar duplicado..
        /// </summary>
        internal static string LinkAlreadyExistsMessageDisabled {
            get {
                return ResourceManager.GetString("LinkAlreadyExistsMessageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certo! Vou avisar que o link já existe..
        /// </summary>
        internal static string LinkAlreadyExistsMessageEnabled {
            get {
                return ResourceManager.GetString("LinkAlreadyExistsMessageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😖 Cara! Esse link não abriu. Não vou salvar por enquanto não.
        ///😱 Tem certeza que este link está certo? Não foi pra lugar nenhum.
        ///😵 Tem alguma coisa errada com este link..
        /// </summary>
        internal static string LinkInvalid {
            get {
                return ResourceManager.GetString("LinkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👍 Salvei seu link!
        ///👊 Deixa que eu guardo este link para você.
        ///😀 Guardei este endereço!
        ///💾 Este link não escapa, tá salvo!
        ///😜 Hum... Parece um conteúdo interessante. Deixa eu guardar aqui...
        ///😬 Tá salvo o link, em nome de Odin!
        ///🙏 Como emissário de São Longuinho, guardei o link pra ficar fácil de encontrar depois.
        ///👌 Opa! Guardei esse link.
        ///👜 Guardei o link no meu bolso aqui.
        ///✍ Bacana este link, vou guardar aqui pra não perder.
        ///🤗 Link salvo! Pode ir mandando que eu tô guardando..
        /// </summary>
        internal static string LinkSaved {
            get {
                return ResourceManager.GetString("LinkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👉 Com este endereço você consegue recuperar os links salvos no chat{0}: {1}. Guarde este link somente para você, ele é seu passe livre para acesso aos links. Para cada grupo que você participa é necessário gerar um link de acesso, porém, depois de gerado você pode usar qualquer um deles para ver os links de qualquer chat..
        /// </summary>
        internal static string LinksRecover {
            get {
                return ResourceManager.GetString("LinksRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⭐️ Avaliar.
        /// </summary>
        internal static string RateBot {
            get {
                return ResourceManager.GetString("RateBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok! Não vou enviar novamente mensagens confirmando o salvamento do link..
        /// </summary>
        internal static string SavedMessagesDisabled {
            get {
                return ResourceManager.GetString("SavedMessagesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok! Vou enviar mensagens confirmando o salvamento do link..
        /// </summary>
        internal static string SavedMessagesEnabled {
            get {
                return ResourceManager.GetString("SavedMessagesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá! Pessoal do grupo {0}, eu sou o LnkCapture e estou aqui para organizar os links que forem postados por aqui. Podem ir mandando os seus links que estarei guardando todos, menos os duplicados 😜.
        ///
        ///A qualquer momento será possível recuperar os links, basta me enviar o comando /linksurl..
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤖 Iniciar conversa.
        /// </summary>
        internal static string StartChat {
            get {
                return ResourceManager.GetString("StartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Adicionar em um grupo.
        /// </summary>
        internal static string StartGroup {
            get {
                return ResourceManager.GetString("StartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá! Eu sou o LnkCapture. Meu objetivo é salvar todos os links que forem postados nos grupos que você me adicionar. Depois será possível consultar a qualquer momento os links salvos. Clique no botão &quot;Adicionar em um grupo&quot;..
        /// </summary>
        internal static string StartPrivate {
            get {
                return ResourceManager.GetString("StartPrivate", resourceCulture);
            }
        }
    }
}
